name: Build and Deploy to Netlify
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: cd ./task2 && npm install --legacy-peer-deps

      - name: Build and Publish
        run: |
          cd ./task2 && npm run build
          ls -lash
          echo "/*    /index.html   200" > ./dist/_redirects
          echo "Publishing to Netlify..."
          npm install netlify-cli -g --legacy-peer-deps
          netlify deploy --prod --dir=./dist --site="${{secrets.NETLIFY_SITE_ID}}" --auth="${{ secrets.NETLIFY_AUTH_TOKEN }}"
